import type { Metadata } from "next";
import Link from "next/link";
import { SITE_URL } from "@/app/layout";

export const metadata: Metadata = {
  title: "Terms of Service – ValorantViral",
  description: "Terms of Service for ValorantViral AI content generator. Read our acceptable use policy, disclaimers, and limitations of liability.",
  openGraph: { title: "Terms of Service – ValorantViral", url: `${SITE_URL}/terms` },
};

export default function TermsPage() {
  const updated = "May 31, 2026";
  return (
    <main className="min-h-screen page-bg py-20 px-4">
      <div className="max-w-3xl mx-auto">
        <Link href="/" className="inline-flex items-center gap-2 text-[#FF8A94] hover:text-[#FF4655] text-sm mb-8 transition-colors">
          ← Back to Home
        </Link>
        <div className="glass-card p-8 sm:p-12">
          <h1 className="text-3xl font-black text-white mb-2">Terms of Service</h1>
          <p className="text-[#B5B5B5]/50 text-sm mb-10">Last updated: {updated}</p>

          <div className="space-y-8 text-[#B5B5B5] text-sm leading-relaxed">

            <section>
              <h2 className="text-lg font-bold text-white mb-3">1. Acceptance of Terms</h2>
              <p>By accessing or using ValorantViral (&quot;the Service&quot;) at valorant-viral-generator.vercel.app, you agree to be bound by these Terms of Service. If you do not agree, please do not use the Service.</p>
            </section>

            <section>
              <h2 className="text-lg font-bold text-white mb-3">2. Description of Service</h2>
              <p>ValorantViral is a free AI-powered content generation tool that helps Valorant content creators generate titles, captions, hashtags, thumbnail text, and anime hype lines for their video clips. The Service uses third-party AI models (Groq/Llama) to generate content based on user input.</p>
            </section>

            <section>
              <h2 className="text-lg font-bold text-white mb-3">3. Acceptable Use</h2>
              <p className="mb-3">You agree to use the Service only for lawful purposes. You must not:</p>
              <ul className="list-disc list-inside space-y-2 ml-2">
                <li>Use the Service to generate content that is defamatory, harassing, or abusive</li>
                <li>Attempt to reverse-engineer, scrape, or automate requests to the Service</li>
                <li>Use the Service to generate spam or misleading content at scale</li>
                <li>Violate any applicable laws or regulations</li>
                <li>Impersonate other creators, players, or organizations</li>
              </ul>
            </section>

            <section>
              <h2 className="text-lg font-bold text-white mb-3">4. AI-Generated Content Disclaimer</h2>
              <p className="mb-3">All content generated by ValorantViral is produced by artificial intelligence. You acknowledge that:</p>
              <ul className="list-disc list-inside space-y-2 ml-2">
                <li>AI-generated content may be inaccurate, incomplete, or inappropriate</li>
                <li>You are solely responsible for reviewing and editing generated content before use</li>
                <li>ValorantViral does not guarantee that generated content will achieve any specific results (views, engagement, etc.)</li>
                <li>Generated content is not unique and similar outputs may be produced for other users</li>
              </ul>
            </section>

            <section>
              <h2 className="text-lg font-bold text-white mb-3">5. Intellectual Property</h2>
              <p>You retain ownership of the clip descriptions you input. The AI-generated output is provided to you for free use without restriction. ValorantViral retains ownership of the Service itself, including its design, code, and branding.</p>
            </section>

            <section>
              <h2 className="text-lg font-bold text-white mb-3">6. Riot Games Disclaimer</h2>
              <p>VALORANT is a trademark of Riot Games, Inc. ValorantViral is an independent fan tool and is <strong className="text-white">not affiliated with, endorsed by, or sponsored by Riot Games</strong>. All Valorant-related trademarks, agent names, map names, and game content belong to Riot Games.</p>
            </section>

            <section>
              <h2 className="text-lg font-bold text-white mb-3">7. Advertising</h2>
              <p>The Service displays advertisements through Google AdSense. These ads are served by Google and are subject to Google&apos;s advertising policies. We are not responsible for the content of third-party advertisements.</p>
            </section>

            <section>
              <h2 className="text-lg font-bold text-white mb-3">8. Limitation of Liability</h2>
              <p>To the maximum extent permitted by law, ValorantViral and its operators shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising from your use of the Service. The Service is provided &quot;as is&quot; without warranties of any kind.</p>
            </section>

            <section>
              <h2 className="text-lg font-bold text-white mb-3">9. Service Availability</h2>
              <p>We do not guarantee that the Service will be available at all times. We reserve the right to modify, suspend, or discontinue the Service at any time without notice.</p>
            </section>

            <section>
              <h2 className="text-lg font-bold text-white mb-3">10. Changes to Terms</h2>
              <p>We may update these Terms at any time. Continued use of the Service after changes constitutes acceptance of the new Terms.</p>
            </section>

            <section>
              <h2 className="text-lg font-bold text-white mb-3">11. Contact</h2>
              <p>For questions about these Terms, contact us at{" "}
                <a href="mailto:godrikt1408@gmail.com" className="text-[#FF8A94] hover:text-[#FF4655] underline">godrikt1408@gmail.com</a>.
              </p>
            </section>

          </div>
        </div>
        <p className="text-center text-xs text-[#B5B5B5]/30 mt-6">
          VALORANT is a trademark of Riot Games. ValorantViral is not affiliated with Riot Games.
        </p>
      </div>
    </main>
  );
}
